name: Deploy Node.js Application to EC2

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Check if the repo directory exists
            if [ ! -d "/home/ubuntu/my-node-app" ]; then
              # Clone the repo if it doesn't exist
              cd /home/ubuntu
              git clone https://github.com/${{ github.repository }} my-node-app
            fi

            # Navigate to the app directory
            cd /home/ubuntu/my-node-app

            # Pull the latest changes if the repo already exists
            git pull origin main

            # Install dependencies and restart app
            npm install
            pm2 restart all  # or any other method to restart your Node.js app
          EOF
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

          
